CPP  = ~/gccsdk/cross/bin/arm-unknown-riscos-g++
ELF2AIF = ~/gccsdk/cross/bin/elf2aif

CXXFLAGS = -mcpu=arm2 -O3 -DSYS_LITTLE_ENDIAN -DBYPASS_PROTECTION -DVIDEO_LITTLE_ENDIAN
OBJ = bank.o engine.o file.o main.o mixer.o parts.o resource.o serializer.o sfxplayer.o staticres.o sysArc.o util.o video.o vm.o

!RunImage,ff8: $(OBJ)
	$(CPP) $(CXXFLAGS) $(OBJ) -static -o "!RunImage,ff8"
	$(ELF2AIF) "!RunImage,ff8"

all : !RunImage,ff8

clean :
	rm *.o
	rm !RunImage,ff8

%.o : %.cpp
	$(CPP) $(CXXFLAGS) -c $<

